[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "beam_networks"
description = "Solver for Timoshenko beam networks"
readme = "README.md"
authors = [
    { name = "Hannes Holey", email = "hannes.holey@unimi.it" },
    { name = "Stefan Hiemer", email = "stefan.hiemer@unimi.it" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU GPLv3"
]
requires-python = ">=3.10"
dynamic = ["version"]
dependencies = [
    "numpy",
    "scipy",
    "PyYAML"]

[project.optional-dependencies]
io = [
    'meshio',
    'trimesh[easy]',
    'pandas[hdf5]']
viz = [
    'matplotlib',
    'pyvista']
tests = [
    'pytest',
    'pytest-cov']
doc = [
    'sphinx',
    'sphinx-book-theme',
    'myst-nb',
    'jupytext']
solvers = [
    'scikit-sparse',
    'pyamg']

[tool.setuptools.packages.find]
where = ["."]
include = ["beam_networks*"]

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "dirty-tag"

[tool.pytest.ini_options]
testpaths = ["tests"]
