"""Plot assembly timing results.

Left panel  — exact assembly: all matrix formats × vectorized / loop.
Right panels — FEM assembly (BSR, reduced integration):
    * middle: vary n_elem_per_length at fixed poly_order; solid=vec, dashed=loop
    * right:  vary poly_order at fixed n_elem_per_length; solid=vec, dashed=loop

Expected input files (generated by the two run_bench_assembly_*.py scripts):
    time_{bsr,lil,dense}-{0,1}.txt              (exact)
    time_fem-p{1,2,3}-n{1,2,5,10}.txt          (FEM loop)
    time_fem_vec-p{1,2,3}-n{1,2,5,10}.txt      (FEM vectorized)
"""

import os
import numpy as np
import matplotlib.pyplot as plt


BENCH_PATH = os.path.dirname(os.path.abspath(__file__))

# n_elem_per_length to highlight in the "vary p" panel
FIXED_N_ELEM = 5
# poly_order to highlight in the "vary n_elem" panel
FIXED_P = 3

N_ELEM_PER_LENGTH = [1, 2, 5, 10]
POLY_ORDERS = [1, 2, 3]

# Visual maps
P_COLORS = {1: 'C0', 2: 'C1', 3: 'C2'}
N_STYLES = {1: '-', 2: '--', 5: ':', 10: '-.'}
N_MARKERS = {1: 'o', 2: 's', 5: '^', 10: 'D'}


def load(fname):
    path = os.path.join(BENCH_PATH, fname)
    if not os.path.exists(path):
        return None, None
    return np.loadtxt(path, unpack=True)


if __name__ == '__main__':

    plt.style.use(os.path.join(os.path.abspath(os.path.dirname(__file__)), '..', 'beams.mplstyle'))

    fig, axes = plt.subplots(1, 3, figsize=(15, 5), sharey=True, sharex=True)

    # ------------------------------------------------------------------
    # Left: exact assembly
    # ------------------------------------------------------------------
    ax = axes[0]
    ax.set_title('Exact assembly')

    exact_configs = [
        ('bsr-1', '-X',  'C0', 'BSR vec'),
        ('lil-1', '-o',  'C1', 'LIL vec'),
        ('dense-1', '-D', 'C2', 'dense vec'),
        ('bsr-0', '--X', 'C0', 'BSR loop'),
        ('lil-0', '--o', 'C1', 'LIL loop'),
        ('dense-0', '--D', 'C2', 'dense loop'),
    ]

    for label, marker, color, name in exact_configs:
        n, t = load(f'time_{label}.txt')
        if n is None:
            continue
        ax.loglog(n, t, marker, color=color, label=name)

    ax.set_xlabel('DOF')
    ax.set_ylabel('Assembly time (s)')
    ax.legend(ncol=2, fontsize=7)

    # ------------------------------------------------------------------
    # Middle: FEM — vary n_elem_per_length (fixed poly_order = FIXED_P)
    # ------------------------------------------------------------------
    ax = axes[1]
    ax.set_title(f'FEM assembly — vary $n_{{elem}}$ (p={FIXED_P})')

    for n_elem in N_ELEM_PER_LENGTH:
        color = f'C{N_ELEM_PER_LENGTH.index(n_elem)}'
        n, t = load(f'time_fem_vec-p{FIXED_P}-n{n_elem}.txt')
        if n is not None:
            ax.loglog(n, t, '-' + N_MARKERS[n_elem], color=color,
                      label=f'$n_{{elem/L}}$={n_elem} vec')
        n, t = load(f'time_fem-p{FIXED_P}-n{n_elem}.txt')
        if n is not None:
            ax.loglog(n, t, '--' + N_MARKERS[n_elem], color=color,
                      label=f'$n_{{elem/L}}$={n_elem} loop')

    ax.set_xlabel('DOF')
    ax.legend(fontsize=7, ncol=2)

    # ------------------------------------------------------------------
    # Right: FEM — vary poly_order (fixed n_elem_per_length = FIXED_N_ELEM)
    # ------------------------------------------------------------------
    ax = axes[2]
    ax.set_title(f'FEM assembly — vary $p$ ($n_{{elem/L}}$={FIXED_N_ELEM})')

    for p in POLY_ORDERS:
        n, t = load(f'time_fem_vec-p{p}-n{FIXED_N_ELEM}.txt')
        if n is not None:
            ax.loglog(n, t, f'-{N_MARKERS[1]}', color=P_COLORS[p], label=f'p={p} vec')
        n, t = load(f'time_fem-p{p}-n{FIXED_N_ELEM}.txt')
        if n is not None:
            ax.loglog(n, t, f'--{N_MARKERS[1]}', color=P_COLORS[p], label=f'p={p} loop')

    ax.set_xlabel('DOF')
    ax.legend(fontsize=7, ncol=2)

    # plt.tight_layout()
    plt.show()
